services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "84:84"
    networks:
      - npm_network
    restart: unless-stopped
    container_name: bonnici-portfolio-front
    volumes:
      - ./data:/app/data  # Mount data directory (includes database)
    command: pdm run front

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "85:85"
    networks:
      - npm_network
    restart: unless-stopped
    container_name: bonnici-portfolio-admin
    volumes:
      - ./data:/app/data  # Mount data directory (includes database)
    command: >
      /bin/sh -c "
        echo 'Generating admin token...' &&
        pdm run generate_admin_password &&
        echo 'Starting admin service...' &&
        pdm run admin
      "

networks:
  npm_network:
    external: true

volumes:
  db_data:  # Volume for persisting database data 