services:
  bonnici-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "84:84"
    networks:
      - npm_network
    restart: unless-stopped
    container_name: bonnici-portfolio
    volumes:
      - db_data:/app/db  # Persist database files

networks:
  npm_network:
    external: true

volumes:
  db_data:  # Volume for persisting database data 